### PR TITLE
Add python virtual environment

### PR DESCRIPTION
**Pull request by Iam54r1n4**

### CODE REVIEW

**Comment by hiddify-com** [comment]
کامل تست کردی؟
تغییر خیلی بزرگیه ها

**Comment by Iam54r1n4** [comment]
> کامل تست کردی؟ تغییر خیلی بزرگیه ها

توی محیظ development تا حد خوبی تست شد. باید مرج بشه و نصب مستقیم هم تست بشه.

**Review by Moslemkhosravibabadi — APPROVED** [review]

**Review by Moslemkhosravibabadi — APPROVED** [review]

**Comment by jacyimp** [comment]
This broke the installation completely. haproxy cannot be installed during the installation anymore. It fails.

Update fails, clean installation also fails.

**Comment by jacyimp** [comment]
Seems like the cfg for haproxy isn't properly generated

Here's a ls of the haproxy where the cfg should be:

```
root@ubuntu20:/opt/hiddify-manager# ls -la haproxy/
total 60
drwxrwxr-x  2 root root  4096 May  4 23:26 .
drwxr-xr-x 17 root root  4096 May  4 23:24 ..
-rw-r--r--  1 root root   369 Apr 13 18:34 arvan.lst
-rw-r--r--  1 root root   336 Apr 13 18:34 cloudflare.lst
-rw-r--r--  1 root root  2788 Apr 13 18:34 cloudfront.lst
-rw-r--r--  1 root root 13491 May  4 23:11 common.cfg.pj2
-rw-r--r--  1 root root   238 Apr 13 18:34 haproxy.cfg.j2
-rw-r--r--  1 root root  1511 May  4 23:19 hiddify-haproxy.service
-rwxr-xr-x  1 root root   657 Apr 13 18:34 install.sh
-rwxr-xr-x  1 root root   683 Apr 13 18:34 run.sh
-rw-r--r--  1 root root  2698 Apr 13 18:34 singbox.cfg.pj2
-rw-r--r--  1 root root  3939 Apr 13 18:34 xray.cfg.pj2

```

**Comment by jacyimp** [comment]
`/opt/hiddify-manager/current.json` is also empty. It exists but it's empty. Could be a reason as to why jinja isn't processing properly?

**Comment by jacyimp** [comment]
There's error in
`:/opt/hiddify-manager/hiddify-panel# python3 -m hiddifypanel all-configs`

`LookupError: 'sub_full_links_b64_enable' is not among the defined enum values. Enum name: configenum. Possible values: dbvalues, create_easy.., wireguard_e.., ..., path_grpc`

Probably missing db migration for the enum value?

**Comment by jacyimp** [comment]
When installing from the bash, even on a clean install, the jinja.py file in commons, isn't up to date.

I grabbed the latest revision from git, and pasted manually. Ran the install.sh again, and now everything is fine.

There has to be a mismatch between the pulled Hiddify-manager using the bash script; It's not the latest version.

**Pull request merged**
