### PR TITLE
Introducing Hiddify-Manager Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Hiddify-Manager Guru](https://gurubase.io/g/hiddify-manager) to Gurubase. Hiddify-Manager Guru uses the data from this repo and data from the [docs](https://hiddify.com/manager/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Hiddify-Manager Guru", which highlights that Hiddify-Manager now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Hiddify-Manager Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by kursataktas** [comment]
Hi everyone,

Have you had a chance to check this out?

Additionally, I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details about [how to claim a Guru here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by hiddify-com** [comment]
Thanks for your great commit
i have merged your commit

can we add it like a chatbot to our website?

**Comment by kursataktas** [comment]
Thanks for the review. The chatbot is not available yet, but we are planning to develop it. I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) and following our [Twitter account](https://x.com/gurubaseio) to stay updated on new features.

**Comment by hiddify-com** [comment]
can you please give access to hiddify@gmail.com for managing it?

in addition would you please add hiddify-app and hiddify-core repositories also?

**Comment by kursataktas** [comment]
> can you please give access to [hiddify@gmail.com](mailto:hiddify@gmail.com) for managing it?
> 
> in addition would you please add hiddify-app and hiddify-core repositories also?

I’ve assigned it to your Gurubase account. You can find it on the 'My Gurus' page.

There is a one-to-one repo/guru relationship for now. Although I can handle that, Gurubase does not index the codebase, it only indexes text-based files. Therefore, adding the READMEs or text-based GitHub pages as a webpage data source on the Guru Edit page should be sufficient. Let me know if you need help finding how to do that.

**Pull request merged**
